image: docker:stable

stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t avi0n/aqua-telegram-bot:stable .

docker push:
  stage: Push to Docker Hub
  only:
  - dev
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push avi0n/aqua-telegram-bot:dev && docker image rm avi0n/aqua-telegram-bot:stable
 