image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t avi0n/aqua-telegram-bot:3.3-beta1

docker push:
  stage: Push to Docker Hub
  only:
  - dev
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push avi0n/aqua-telegram-bot:3.3-beta1 && docker image rm avi0n/aqua-telegram-bot:3.3-beta1
 